name: Automation

on:
  workflow_dispatch:
    inputs:
      Environment:
        type: choice
        description: 'Environment'
        required: true
        options:
           - dev
           - stg
           - uat
           - prod
jobs:
  build:
    name: config
    runs-on: ubuntu-latest
    environment: ${{ inputs.Environment}}
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild path
      run: |
        sudo apt update && sudo apt-get install wget -y && sudo mkdir -p -m 755 /etc/apt/keyrings \
        && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
        && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
        && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y
        
    - name: Setup MSBuild path
      run: |
        gh auth login --with-token ${{secrets.AUTOMATION_TOKEN}}
        gh variable list --env ${{ inputs.Environment}}
